
nav:

    - 'HOME': index.md

site_name: SkyANT STATIC




###
#  Template
###


docs_dir: .docs
edit_uri: ""


extra:

    generator: true
    homepage: https://skyant.dev
    analytics:
        provider: google
        property: G-1R41YK6WT2

    social:
        
        - icon: fontawesome/brands/square-facebook
          link: https://facebook.com/skyantdev
          name: facebook
        
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/skyantdev
          name: linkedin

        - icon: fontawesome/brands/square-twitter
          link: https://twitter.com/skyantdev
          name: twitter

        - icon: fontawesome/solid/house
          link: https://skyant.dev
          name: home


theme: 
    name: material
    favicon: https://static.skyant.dev/common/img/icons/ant-512.drawio.png
    logo: https://static.skyant.dev/common/img/icons/ant-512.drawio.png
    palette:
        primary: amber
        accent: deep purple
    font:
        text: Montserrat
        code: Roboto Mono
    icon:
        repo: fontawesome/brands/gitlab
    features:
        - search.highlight
        - search.suggest
        - navigation.tabs
        - content.code.annotate
        - content.tabs.link


extra_css:
    - https://static.skyant.dev/common/css/mkdocs/skyant.css
    - https://static.skyant.dev/common/css/mkdocs/hide-title.css
    - https://static.skyant.dev/common/css/mkdocs/hide-versions.css


plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: true
                    show_root_full_path: false
                    show_root_toc_entry: false
                    show_bases: false
                    show_category_heading: false
    - search
    - section-index
    - glightbox
    - include-markdown


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - footnotes
    - attr_list
    - pymdownx.tabbed:
        alternate_style: true 
    - md_in_html
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
