
nav:

    - 'HOME': index.md

site_name: Omnicloud STATIC





###
#  Template
###


docs_dir: .
edit_uri: ""


extra:

    generator: true
    homepage: https://docs.omnicloud.world
    #analytics:
    #    provider: google
    #    property: G-1R41YK6WT2

    social:
        
        - icon: fontawesome/brands/square-facebook
          link: https://facebook.com/omnicloudworld
          name: facebook
        
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/omnicloudworld
          name: linkedin

        - icon: fontawesome/solid/house
          link: https://omnicloud.world
          name: home


theme: 
    name: material
    favicon: https://static.omnicloud.world/common/img/icons/omni-color02.png
    logo: https://static.omnicloud.world/common/img/icons/omni.drawio.png
    palette:
        primary: amber
        accent: deep purple
    font:
        text: Comfortaa
        code: Montserrat
    icon:
        repo: fontawesome/brands/github
    features:
        - search.highlight
        - search.suggest
        - navigation.tabs
        - content.code.annotate
        - content.tabs.link


extra_css:
    - https://static.omnicloud.world/common/css/mkdocs/main.css
    - https://static.omnicloud.world/common/css/mkdocs/hide-title.css
    - https://static.omnicloud.world/common/css/mkdocs/hide-versions.css
    #- https://static.omnicloud.world/common/css/mkdocs/big-versions.css


plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: true
                    show_root_full_path: false
                    show_root_toc_entry: false
                    show_bases: false
                    show_category_heading: false
    - search
    - section-index
    - glightbox
    - include-markdown
    - same-dir


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - footnotes
    - attr_list
    - pymdownx.tabbed:
        alternate_style: true 
    - md_in_html
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true